export PATH="$PATH:/usr/local/sbin"
export PATH="$PATH:/usr/local"
export PATH="$PATH:$DOTFILES/bin"
export PATH="$PATH:/usr/local/opt/go/libexec/bin"
export PATH="$PATH:$HOME/go/bin"
export PATH="$PATH:/usr/local/opt/google-cloud-sdk/bin"
export PATH="$PATH:$HOME/dev/nu/nucli"
