#!/bin/bash

###############################################################################
# Local LLM Setup (Ollama)
#
# Usage:
#   ./setup-llm.sh                    Install, interactive model pick, pull
#   ./setup-llm.sh --pull-only        Pull models from saved config
#   ./setup-llm.sh --install-only     Install Ollama + ports only
#   ./setup-llm.sh --select-only      fzf model picker, save config
#   ./setup-llm.sh --non-interactive  Use OLLAMA_MODELS from .setupconf
###############################################################################

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# shellcheck source=lib/setup-utils.sh
source "$DOTFILES_ROOT/lib/setup-utils.sh"
# shellcheck source=lib/llm-hardware.sh
source "$DOTFILES_ROOT/lib/llm-hardware.sh"
# shellcheck source=setup/llm.defaults.sh
source "$SCRIPT_DIR/llm.defaults.sh"

PULL_ONLY=false
INSTALL_ONLY=false
SELECT_ONLY=false
NON_INTERACTIVE=false

while [[ $# -gt 0 ]]; do
    case $1 in
        --pull-only) PULL_ONLY=true; shift ;;
        --install-only) INSTALL_ONLY=true; shift ;;
        --select-only) SELECT_ONLY=true; shift ;;
        --non-interactive) NON_INTERACTIVE=true; shift ;;
        -h|--help)
            sed -n '3,13p' "$0" | cut -c3-
            exit 0
            ;;
        *)
            fail_fast "Unknown option: $1 (use --help)"
            ;;
    esac
done

if [[ -f "$DOTFILES_ROOT/.setupconf" ]]; then
    # shellcheck source=/dev/null
    source "$DOTFILES_ROOT/.setupconf"
fi

export SKIP_LLM_PULL="${SKIP_LLM_PULL:-false}"
export OLLAMA_MODELS="${OLLAMA_MODELS:-$DEFAULT_OLLAMA_MODELS}"

find_brew() {
    if command -v brew >/dev/null 2>&1; then
        command -v brew
    elif [[ -x /opt/homebrew/bin/brew ]]; then
        echo /opt/homebrew/bin/brew
    elif [[ -x /usr/local/bin/brew ]]; then
        echo /usr/local/bin/brew
    else
        return 1
    fi
}

ollama_base_url() {
    echo "http://${LLM_OLLAMA_HOST}:${LLM_OLLAMA_PORT}"
}

write_llm_env_files() {
    local env_path="$DOTFILES_ROOT/config/llm.env"
    local user_env="$LLM_ENV_FILE"

    mkdir -p "$LLM_CONFIG_DIR" "$(dirname "$env_path")"

    local default_model="${LLM_DEFAULT_MODEL:-}"
    default_model="${default_model:-${OLLAMA_MODELS%% *}}"

    cat > "$env_path" <<EOF
# Generated by make llm — deterministic local LLM ports
LLM_OLLAMA_HOST=${LLM_OLLAMA_HOST}
LLM_OLLAMA_PORT=${LLM_OLLAMA_PORT}
LLM_OPENAI_PORT=${LLM_OPENAI_PORT}
LLM_PORT_OPEN_WEBUI=${LLM_PORT_OPEN_WEBUI}
LLM_PORT_LMSTUDIO=${LLM_PORT_LMSTUDIO}
LLM_DEFAULT_MODEL=${default_model}

export OLLAMA_HOST="\${LLM_OLLAMA_HOST}:\${LLM_OLLAMA_PORT}"
export LLM_API_BASE="http://\${OLLAMA_HOST}"
export LLM_OPENAI_BASE="http://\${OLLAMA_HOST}/v1"
export OPENAI_API_BASE="\${LLM_OPENAI_BASE}"
export OPENAI_BASE_URL="\${LLM_OPENAI_BASE}"
export OPENAI_API_KEY="ollama"
LLM_DEFAULT_MODEL=${LLM_DEFAULT_MODEL:-}
export LLM_DEFAULT_MODEL
EOF

    cp "$env_path" "$user_env"
    log_success "Wrote ${env_path} and ${user_env}"
}

write_llm_models_file() {
    local models="$1"
    local first
    first="${models%% *}"
    mkdir -p "$LLM_CONFIG_DIR"
    printf '%s\n' "$models" | tr ' ' '\n' | grep -v '^$' > "$LLM_MODELS_FILE"
    if [[ -n "$first" ]]; then
        printf '%s\n' "$first" > "${LLM_CONFIG_DIR}/llm.default"
        export LLM_DEFAULT_MODEL="$first"
    fi
}

update_setupconf_models() {
    local models="$1"
    local conf="$DOTFILES_ROOT/.setupconf"

    if [[ ! -f "$conf" ]]; then
        printf '\n# Local LLM models (make llm)\nOLLAMA_MODELS="%s"\n' "$models" >> "$conf"
        return 0
    fi

    if grep -q '^OLLAMA_MODELS=' "$conf"; then
        if [[ "$OSTYPE" == darwin* ]]; then
            sed -i '' "s|^OLLAMA_MODELS=.*|OLLAMA_MODELS=\"${models}\"|" "$conf"
        else
            sed -i "s|^OLLAMA_MODELS=.*|OLLAMA_MODELS=\"${models}\"|" "$conf"
        fi
    else
        printf '\nOLLAMA_MODELS="%s"\n' "$models" >> "$conf"
    fi
}

select_models_interactive() {
    local preselected="$OLLAMA_MODELS"
    local picked

  if [[ "$NON_INTERACTIVE" == "true" ]]; then
        log_info "Non-interactive: using OLLAMA_MODELS from config"
        return 0
    fi

    if [[ ! -t 0 ]] && [[ ! -t 1 ]]; then
        log_warning "Not a TTY — skipping fzf (use --non-interactive or OLLAMA_MODELS)"
        return 0
    fi

    log_step "Choose models to install (fzf)"
    picked="$(bash "$SCRIPT_DIR/setup-llm-select.sh" --preselected "$preselected")"
    OLLAMA_MODELS="$picked"
    export OLLAMA_MODELS

    write_llm_models_file "$OLLAMA_MODELS"
    update_setupconf_models "$OLLAMA_MODELS"
    log_success "Selected models: $OLLAMA_MODELS"
}

configure_ollama_server_ports() {
    local hostport="${LLM_OLLAMA_HOST}:${LLM_OLLAMA_PORT}"
    export OLLAMA_HOST="$hostport"

    write_llm_env_files

    if is_linux && command -v systemctl >/dev/null 2>&1; then
        local dropin_dir="/etc/systemd/system/ollama.service.d"
        if [[ -w /etc/systemd/system ]] || sudo -n true 2>/dev/null; then
            log_step "Configuring Ollama systemd port (${hostport})"
            sudo mkdir -p "$dropin_dir"
            printf '%s\n' "[Service]" "Environment=OLLAMA_HOST=${hostport}" | \
                sudo tee "$dropin_dir/dotfiles-ports.conf" >/dev/null
            sudo systemctl daemon-reload 2>/dev/null || true
        else
            log_warning "Could not write systemd drop-in; set OLLAMA_HOST=${hostport} manually"
        fi
    fi

    if is_macos; then
        # Persist for GUI/login sessions; brew services inherits from user environment on some setups
        launchctl setenv OLLAMA_HOST "$hostport" 2>/dev/null || true
    fi

    log_success "Ollama API fixed at $(ollama_base_url) (OpenAI-compat: $(ollama_base_url)/v1)"
}

install_ollama_macos() {
    local brew_bin
    brew_bin="$(find_brew)" || fail_fast "Homebrew is required. Run make setup-darwin first."

    if "$brew_bin" list ollama >/dev/null 2>&1; then
        log_info "Ollama is already installed via Homebrew"
    else
        log_step "Installing Ollama (MLX-accelerated on Apple Silicon)"
        "$brew_bin" install ollama
    fi

    configure_ollama_server_ports

    log_step "Starting Ollama service (OLLAMA_HOST=${OLLAMA_HOST})"
    OLLAMA_HOST="${OLLAMA_HOST}" "$brew_bin" services restart ollama 2>/dev/null || \
        OLLAMA_HOST="${OLLAMA_HOST}" "$brew_bin" services start ollama
}

install_ollama_linux() {
    if ! command -v ollama >/dev/null 2>&1; then
        log_step "Installing Ollama via official installer"
        curl -fsSL https://ollama.com/install.sh | sh
    else
        log_info "Ollama is already installed"
    fi

    configure_ollama_server_ports

    if command -v systemctl >/dev/null 2>&1; then
        sudo systemctl enable ollama 2>/dev/null || true
        sudo systemctl restart ollama 2>/dev/null || sudo systemctl start ollama 2>/dev/null || true
    fi
}

wait_for_ollama() {
    local url attempts=0 max_attempts=30
    url="$(ollama_base_url)"

    log_step "Waiting for Ollama API (${url})"
    while ! curl -sf "${url}/api/tags" >/dev/null 2>&1; do
        attempts=$((attempts + 1))
        if [[ $attempts -ge $max_attempts ]]; then
            fail_fast "Ollama did not become ready at ${url}"
        fi
        sleep 2
    done
    log_success "Ollama API is ready at ${url}"
}

pull_models() {
    if [[ "${SKIP_LLM_PULL}" == "true" ]]; then
        log_info "SKIP_LLM_PULL=true — skipping model downloads"
        return 0
    fi

    # shellcheck disable=SC2206
    local models=($OLLAMA_MODELS)
    if [[ ${#models[@]} -eq 0 ]]; then
        log_warning "No models configured"
        return 0
    fi

    wait_for_ollama

    for model in "${models[@]}"; do
        log_step "Pulling model: $model"
        OLLAMA_HOST="${LLM_OLLAMA_HOST}:${LLM_OLLAMA_PORT}" ollama pull "$model"
        log_success "Pulled $model"
    done
}

print_usage_hints() {
    local primary="${OLLAMA_MODELS%% *}"
    local base
    base="$(ollama_base_url)"

    llm_hardware_summary

    echo ""
    log_success "Local LLM setup complete"
    echo ""
    echo "  Hardware:  ${LLM_CPU_LABEL} · ${LLM_RAM_TOTAL_GB}GB RAM · ~${LLM_RAM_AVAILABLE_GB}GB for models"
    echo "  Entrypoint: llm chat | llm ask \"...\" | llm api"
    echo "  API:       ${base}/v1  (all models; set model per request)"
    echo "  Default:   ${primary:-<run llm pick>}"
    echo "  Ports:     Ollama=${LLM_OLLAMA_PORT}  OpenWebUI(reserved)=${LLM_PORT_OPEN_WEBUI}  LMStudio(reserved)=${LLM_PORT_LMSTUDIO}"
    echo "  Config:    ${LLM_ENV_FILE}"
    echo "  Re-pick:   make llm-select"
    echo ""
}

main() {
    print_header "Local LLM Setup (Ollama)"

    if [[ "$SELECT_ONLY" == "true" ]]; then
        select_models_interactive
        print_usage_hints
        return 0
    fi

    if [[ "$PULL_ONLY" == "true" ]]; then
        command -v ollama >/dev/null 2>&1 || fail_fast "Ollama not installed. Run: make llm"
        if [[ -f "$LLM_ENV_FILE" ]]; then
            # shellcheck source=/dev/null
            source "$LLM_ENV_FILE"
        fi
        pull_models
        print_usage_hints
        return 0
    fi

    if is_macos; then
        install_ollama_macos
    elif is_linux; then
        install_ollama_linux
    else
        fail_fast "Unsupported OS: $OSTYPE"
    fi

    select_models_interactive

    if [[ "$INSTALL_ONLY" == "true" ]]; then
        log_success "Ollama installed; models saved but not pulled (install-only)"
        print_usage_hints
        return 0
    fi

    pull_models
    print_usage_hints
}

main "$@"
